/**
 * 100 requests a working agent (solo or on a team) really sends. `expect` is the intent a smart assistant should route to
 * ("general" = open question for the AI), `data` is what Mila must be able to pull to answer it well.
 * Data keys: record = property record, listing = active listing/MLS facts, avm = value estimate + comps, rent = rental listings/estimates,
 * area = neighborhood facts (schools, walkability, crime, flood), market = live market stats (web search), web = open web research,
 * own = the agent's own saved data (contacts, calendar, listings), none = no outside data.
 */
export type Data = "record" | "listing" | "avm" | "rent" | "area" | "market" | "web" | "own" | "none";
export interface Scenario { q: string; expect: string | string[]; data: Data[]; group: string }
const S = (group: string, rows: [string, string | string[], Data[]][]): Scenario[] => rows.map(([q, expect, data]) => ({ q, expect, data, group }));

export const SCENARIOS: Scenario[] = [
  ...S("Property lookup (any address, any unit)", [
    ["Pull up 4812 Bluebonnet Ln, Austin TX 78704", "prep_property", ["record", "listing", "avm"]],
    ["What can you tell me about 1600 Pennsylvania Ave NW Washington DC", "prep_property", ["record"]],
    ["Look up 350 5th Ave Apt 32B New York NY 10118", "prep_property", ["record", "avm"]],
    ["Get me info on 88 Harbor Point Unit 1204 Stamford CT", "prep_property", ["record", "listing"]],
    ["Run the numbers on 2217 Live Oak Dr Dallas TX", "prep_property", ["record", "avm"]],
    ["Research 212 Linden Rd Germantown MD for me", "prep_property", ["record"]],
    ["What is 725 Park Avenue Unit 4C Chicago IL worth?", ["prep_property", "general", "client_search"], ["avm"]],
    ["Pull the tax history and last sale on 9 Maple Ct, Raleigh NC 27601", "prep_property", ["record"]],
    ["Prep me on 1450 Brickell Bay Dr #2305 Miami FL", "prep_property", ["record", "avm"]],
    ["Give me details for 77 Sunset Blvd Los Angeles CA 90028", "prep_property", ["record"]],
  ]),
  ...S("Active listings & rentals", [
    ["What new listings hit the market in Rockville MD this week?", "new_listings", ["listing"]],
    ["Show me the newest homes in Austin TX under $600k", "new_listings", ["listing"]],
    ["Any new 3 bedroom listings in Gaithersburg today?", "new_listings", ["listing"]],
    ["What just listed in 20850?", "new_listings", ["listing"]],
    ["Find me 2 bedroom apartments for rent in Baltimore under $2,200", ["find_property", "client_search", "new_listings", "general"], ["rent"]],
    ["What are 1 bedroom rentals going for in Arlington VA right now?", ["market", "general", "client_search"], ["rent"]],
    ["Show me condos listed in the last 3 days in Bethesda", "new_listings", ["listing"]],
    ["Are there any townhomes under $450k in Frederick that came on this week?", "new_listings", ["listing"]],
    ["What is the rent estimate for 123 Main St Apt 4 Silver Spring MD?", ["prep_property", "general", "client_search"], ["rent"]],
    ["Is 4812 Bluebonnet Ln still active or did it sell?", ["prep_property", "general"], ["listing"]],
  ]),
  ...S("Market & pricing", [
    ["What's happening in the Montgomery County market?", "market", ["market"]],
    ["What are mortgage rates today?", "market", ["market"]],
    ["How many days on market is the average home in Bethesda right now?", "market", ["market"]],
    ["What's the median home price in Frederick County?", "market", ["market"]],
    ["Is it a buyer's or seller's market in Austin?", "market", ["market"]],
    ["Give me a quick market update I can send to my sphere", "market", ["market"]],
    ["Help me price a 4 bed colonial in Potomac, what comps should I pull?", ["general", "prep_property", "client_search"], ["avm", "market"]],
    ["What should I list 22 Elm Court Bethesda at?", ["general", "prep_property", "client_search"], ["avm"]],
    ["How are inventory levels trending in my area?", "market", ["market"]],
    ["What's the price per square foot in Rockville condos?", ["market", "general", "client_search"], ["market"]],
  ]),
  ...S("Client search briefs & matching", [
    ["I have a buyer looking for a 3 bedroom home in Frederick under $500k with a garage and good schools, find options", ["find_property", "client_search", "new_listings", "general"], ["listing", "area"]],
    ["My clients want to relocate from Seattle to the DC area, walkable, great schools, under $900k, find the best neighborhoods", ["general", "client_search", "market"], ["market", "area"]],
    ["Find something for Aisha", "find_property", ["own", "listing"]],
    ["Who in my database is looking for a 3 bed townhome in Gaithersburg?", "find_contacts", ["own"]],
    ["Show me my buyers under $500k", "find_contacts", ["own"]],
    ["I have an investor client who wants cash flowing duplexes in Baltimore, what should I look at", ["general", "client_search", "market"], ["market", "rent"]],
    ["Retired couple wants a single-level home near Annapolis, low maintenance, walkable to restaurants, find some neighborhoods", ["general", "client_search"], ["area", "web"]],
    ["First time buyer, $350k budget, FHA, near the Metro, what areas make sense?", ["general", "market", "client_search"], ["market", "area"]],
    ["Which of my leads haven't I talked to in 3 weeks?", "priorities", ["own"]],
    ["Match my new listing to my buyers", ["find_contacts", "general"], ["own"]],
  ]),
  ...S("Apartments & relocation (the hard ones)", [
    ["Clients want a luxury apartment with a rooftop pool, floor-to-ceiling windows, under $3,000, in Nashville", ["client_search", "general"], ["rent", "area", "web"]],
    ["Pet friendly 2 bedroom with parking in Denver under $2,400, cannabis legal, walkable at night, find the best buildings", ["client_search", "general"], ["rent", "area", "web"]],
    ["Is Midtown Atlanta safe to walk at night?", ["general", "client_search"], ["area", "web"]],
    ["Compare Austin and Raleigh for a young couple moving from Maryland", ["general", "client_search"], ["market", "area", "web"]],
    ["What do residents say about The Residences at Brickell?", ["general", "client_search"], ["web"]],
    ["Does that building have a 3D tour?", ["general", "client_search"], ["web"]],
    ["What are the best apartment buildings in Jersey City with balconies under $2,800", ["client_search", "general"], ["rent", "web"]],
    ["Find me a place in Portland where recreational cannabis is legal and the walk score is high, 1 bed under $2,000", ["client_search", "general"], ["rent", "area", "web"]],
    ["Look for apartments with specified criteria", ["client_search", "find_property", "general"], ["rent", "web"]],
    ["Which neighborhoods in Chicago are upscale young urban with a $2,500 budget?", ["general", "client_search"], ["area", "rent", "web"]],
  ]),
  ...S("Calendar, showings & open houses", [
    ["Showing at 456 Oak Lane Sunday at 3 PM", "create_event", ["own"]],
    ["Set up an open house at 123 Main Street Saturday 1-4", "open_house", ["own", "record"]],
    ["What's on my calendar tomorrow?", "agenda", ["own"]],
    ["Move my 2pm showing to 4", "move_event", ["own"]],
    ["Cancel my Friday open house", "cancel_event", ["own"]],
    ["I'm out of town next Thursday and Friday", "time_off", ["own"]],
    ["Am I free Wednesday at 3?", "agenda", ["own"]],
    ["Remind me to call the Hendersons tomorrow at 9", "reminder", ["own"]],
    ["How's my week looking?", "week_overview", ["own"]],
    ["Schedule a buyer consult with Priya Patel Thursday 11am", "create_event", ["own"]],
  ]),
  ...S("Follow-ups, CRM & team", [
    ["Who do I need to follow up with today?", "priorities", ["own"]],
    ["Text Marcus that the inspection is Tuesday at 10", "draft_text", ["own"]],
    ["Draft a follow up to everyone who came to the open house at 12 Oak St", "batch_followups", ["own"]],
    ["I have a new buyer named Dana Kim, looking for a condo in Bethesda around $450k, wants to move in 3 months", "new_contact", ["own"]],
    ["Dana Kim just called, she wants to see two more places this weekend", "log_interaction", ["own"]],
    ["Email Sarah the updated comps for her listing", "draft_email", ["own", "avm"]],
    ["Who's gone cold in my pipeline?", "priorities", ["own"]],
    ["What's Priya's number?", "recall", ["own"]],
    ["How much am I making in my pipeline right now?", "pipeline_value", ["own"]],
    ["Brief me for my 2 PM meeting with John Alvarez", "meeting_prep", ["own"]],
  ]),
  ...S("Listing prep & transactions", [
    ["I'm listing 1231 Main Street Gaithersburg MD next Thursday, get me ready", "listing_ready", ["own", "record"]],
    ["What am I missing for 22 Elm Court?", "what_missing", ["own"]],
    ["Add my listing 22 Elm Court Bethesda MD, 3 bed 2 bath, $650k", "add_listing", ["own"]],
    ["Price drop on 12 Oak St, now $425k", "update_listing", ["own"]],
    ["Our offer on 9 Pine Way was accepted, closing June 30", "transaction", ["own"]],
    ["We closed on 77 Cedar Ln for $512,000", "closed_deal", ["own"]],
    ["Make me a showing sheet for 22 Elm Court", "showing_sheet", ["own"]],
    ["Write a just listed post for 22 Elm Court", "social_post", ["own"]],
    ["Draft an email to my list about the open house on Sunday", "email_audience", ["own"]],
    ["Give me 3 Instagram carousels for my new listing", "social_post", ["own"]],
  ]),
  ...S("Strategy, negotiation & compliance (expert chat)", [
    ["A buyer's agent just lowballed me on Brookside, how do I handle it?", "general", ["none"]],
    ["Write a script for a FSBO seller who says they don't need an agent", "general", ["none"]],
    ["How should I respond when sellers want to list 10% over market?", "general", ["none"]],
    ["What's the best way to get a past client to refer me?", "general", ["none"]],
    ["Walk me through what happens after an accepted offer in Maryland", "general", ["none"]],
    ["Can I say a neighborhood is good for families in my listing description?", "general", ["none"]],
    ["Give me a 30 day plan to get 3 new listings", "general", ["none"]],
    ["What are the pros and cons of an escalation clause for my buyer?", "general", ["none"]],
    ["How do I explain closing costs to a first time buyer?", "general", ["none"]],
    ["Help me with an objection: 'your commission is too high'", "general", ["none"]],
  ]),
  ...S("Casual & messy phrasing", [
    ["hey", "smalltalk", ["none"]],
    ["thanks!", "smalltalk", ["none"]],
    ["any1 tour 12 oak st tmrw 2pm", ["create_event", "general"], ["own"]],
    ["pls move showing to sat 11", "move_event", ["own"]],
    ["whats on today", "agenda", ["own"]],
    ["need to follow up with ppl from sunday", ["priorities", "showing_followups", "batch_followups", "general"], ["own"]],
    ["undo that", "undo", ["own"]],
    ["can u add a buyer john smith 301-555-0188 wants 3br rockville", "new_contact", ["own"]],
    ["which houses r new in frederick", "new_listings", ["listing"]],
    ["how much is my pipeline", "pipeline_value", ["own"]],
  ]),
];
