// 50 hard, realistic conversations a working agent might have. Real-style addresses, typos, pronouns, corrections, two asks in one message.
// "expect" is a loose check on the LAST turn's reply (regex source) or on saved data ("events:n", "contacts:n", "tasks>=n").
export interface Convo { id: string; turns: string[]; expect?: string[] }
export const CONVOS: Convo[] = [
  { id: "01 showing then move", turns: ["Showing at 1227 Main Street Gaithersburg MD tomorrow at 2pm with the Turners", "move it to 4", "make it saturday instead"], expect: ["Added", "Moved to Friday at 4", "Moved to Saturday"] },
  { id: "02 two bookings", turns: ["Lunch with Priya Wednesday at noon and a showing at 99 Oak Ave Germantown Thursday 5:30pm"], expect: ["events:2"] },
  { id: "03 open house", turns: ["Open house at 14 Chestnut Ln Bethesda MD 20814 this Sunday 1-3pm", "what did I just schedule?"], expect: ["prepared your open house", "14 Chestnut Lane"] },
  { id: "04 offer accepted", turns: ["Offer accepted on 7712 Old Georgetown Rd Bethesda, closing Nov 20, inspection in 10 days, financing contingency Nov 5"], expect: ["built the timeline"] },
  { id: "05 new buyer full", turns: ["New buyer Maria Gonzales, maria.g@gmail.com, 301-555-0188, pre-approved $550k, wants a 3 bed near Rockville", "what's Maria looking for?"], expect: ["Maria Gonzales is set up", "Rockville"] },
  { id: "06 text her", turns: ["New buyer Dana Whitfield, 301-555-0142", "text her that the showing moved to 4"], expect: ["Set up", "text to Dana"] },
  { id: "07 text by name", turns: ["Text Dana I'm running 10 min late"], expect: ["text to Dana"] },
  { id: "08 email by name", turns: ["New seller Tom Reyes, tom@example.com", "email Tom the listing agreement for 45 Pinecrest Dr"], expect: ["set up", "draft"] },
  { id: "09 add as lead existing", turns: ["I have a new buyer named Michelle Turner", "add michelle as a lead already comeon"], expect: ["set up", "Michelle Turner is now a lead"] },
  { id: "10 time answer bare", turns: ["Going to do a showing tomorrow with the turners at 1227 Main Street in Gaithersburg. Set me up", "They said 2"], expect: ["What time", "2:00 PM"] },
  { id: "11 time answer word", turns: ["Showing at 12 Oak Lane tomorrow", "two"], expect: ["What time", "2:00 PM"] },
  { id: "12 reminder", turns: ["remind me tomorrow at 9 to call Priya about the appraisal"], expect: ["emind"] },
  { id: "13 reminder ask time", turns: ["remind me to send the CMA", "friday at 10"], expect: ["When", "emind"] },
  { id: "14 cancel", turns: ["Showing at 55 Pine Road Friday at 3pm", "cancel it"], expect: ["Added", "confirm"] },
  { id: "15 block day", turns: ["I'm off next Friday", "anything on friday?"], expect: ["", ""] },
  { id: "16 listing appt", turns: ["Put me down for a listing appointment with the Hendersons at 22 Birch St Frederick Tuesday at 6pm"], expect: ["Added"] },
  { id: "17 listing add", turns: ["I just got a listing at 310 Laurel Ave Silver Spring MD, 4 bed 3 bath, $725k, sellers are the Parks"], expect: ["Saved your listing"] },
  { id: "18 post for it", turns: ["I just got a listing at 310 Laurel Ave Silver Spring MD, 4 bed 3 bath, $725k", "make me an instagram post for it"], expect: ["Saved your listing", "310 Laurel"] },
  { id: "19 checklist", turns: ["I just got a listing at 310 Laurel Ave Silver Spring MD", "what's missing for this listing?"], expect: ["Saved", ""] },
  { id: "20 week", turns: ["Showing at 12 Oak Lane Friday at 3pm", "what does my week look like?"], expect: ["Added", ""] },
  { id: "21 priorities", turns: ["Who should I follow up with today?"], expect: [""] },
  { id: "22 pipeline", turns: ["New buyer Sam Park, budget $600k", "what's my pipeline worth?"], expect: ["set up", ""] },
  { id: "23 closed deal", turns: ["Offer accepted on 88 Willow Court, closing October 30", "I closed on 88 Willow Court today, sold for 612k, buyers were the Parks"], expect: ["built the timeline", "Congratulations"] },
  { id: "24 log call", turns: ["New buyer Dana Whitfield", "log a call with Dana: she's pre-approved and I'll send her three listings tonight"], expect: ["set up", "Logged your call"] },
  { id: "25 typo showing", turns: ["I have an showinge at 1227 Main Street Gaithersburg for the turner family. They went to see it tmr at 2pm. Get me prepared for it"], expect: ["Added"] },
  { id: "26 pronoun email", turns: ["New buyer Aisha Khan, aisha@example.com", "tell her I can't help her find apartments"], expect: ["set up", "draft"] },
  { id: "27 move wrong day", turns: ["Showing at 12 Oak Lane Sunday at 1pm", "actually make it monday"], expect: ["Added", "Moved"] },
  { id: "28 conflict", turns: ["Showing at 12 Oak Lane Friday at 3pm", "Showing at 99 Elm Court Friday at 3pm"], expect: ["Added", "overlap|already|conflict"] },
  { id: "29 past time", turns: ["Showing at 12 Oak Lane today at 6am"], expect: ["passed|already"] },
  { id: "30 address no city", turns: ["I have a listing at 77 Maple Drive"], expect: ["city|where|Saved"] },
  { id: "31 vague", turns: ["help"], expect: [""] },
  { id: "32 thanks", turns: ["thanks mila"], expect: [""] },
  { id: "33 new contact lowercase", turns: ["new buyer named dana whitfield looking for a 3 bedroom around 600k in bethesda"], expect: ["Dana Whitfield is set up"] },
  { id: "34 couple names", turns: ["I met a couple at the open house yesterday, Dave and Linda Kim, they want to sell their townhouse"], expect: [""] },
  { id: "35 note memory", turns: ["I never show on Sundays", "showing at 12 Oak Lane Sunday at 2"], expect: [""] },
  { id: "36 recall", turns: ["New buyer Sean O'Malley wants a big backyard and a garage", "tell me about Sean"], expect: ["set up", "backyard"] },
  { id: "37 prep meeting", turns: ["New buyer Maria Gonzales", "Showing with Maria tomorrow at 3pm at 9 Elm Court", "prep me for my 3pm with Maria"], expect: ["set up", "Added", "Maria"] },
  { id: "38 flyer", turns: ["Open house at 14 Chestnut Ln Bethesda MD Sunday 1-3pm", "make a caption for it"], expect: ["prepared", "Chestnut"] },
  { id: "39 bulk email ask", turns: ["email everyone I met this week about the open house"], expect: [""] },
  { id: "40 delete contact", turns: ["New buyer Test Person", "delete Test Person"], expect: ["set up", "confirm|sure|delete"] },
  { id: "41 spanish name", turns: ["New buyer José Hernández, jose@example.com, budget $450k"], expect: ["set up"] },
  { id: "42 double space", turns: ["showing   at 12 Oak Lane   tomorrow   at   2pm"], expect: ["Added"] },
  { id: "43 shouty", turns: ["SHOWING AT 12 OAK LANE TOMORROW AT 2PM"], expect: ["Added"] },
  { id: "44 range time", turns: ["Open house at 12 Oak Lane Saturday 12-2"], expect: ["prepared"] },
  { id: "45 weekday abbrev", turns: ["inspection at 99 Elm Ct thurs 9am"], expect: ["Added|passed"] },
  { id: "46 correction name", turns: ["New buyer Dana Whitfield", "no her name is Dana Whitford"], expect: ["set up", ""] },
  { id: "47 multi contact", turns: ["Add Ann Lee ann@x.com and Bob Ray bob@y.com as buyers"], expect: [""] },
  { id: "48 price question", turns: ["what should I list 45 Pinecrest Dr Silver Spring at?"], expect: [""] },
  { id: "49 market question", turns: ["what's the market like in Bethesda right now?"], expect: [""] },
  { id: "50 apartments", turns: ["find apartments for my client in Rockville under $2000 with 2 beds"], expect: [""] },
];
